name: CI - Maven TestNG Selenium

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true                 # helps your Base detect CI and enable headless mode
      MAVEN_OPTS: -Xmx2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Verify java & mvn
        run: |
          java -version
          mvn -v

      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests
        # -B is batch mode (non-interactive)
        run: mvn -B -DskipTests=false clean test
        # If you want to run a specific suite file:
        # run: mvn -B -Dsurefire.suiteXmlFiles=testng.xml clean test

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload Test output (logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-output-log
          path: |
            target/surefire-reports/*.txt
            target/surefire-reports/*.xml
            target/surefire-reports/*.html
